modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="cecm"
version="1.0.0"
displayName="CE's Compat & More"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="CEntertain"
description="Adds compatibility between CEMM and other mods in CE's Adventure & More"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cecm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



